---
# DataConfig.prop setting. The spaCy dataset from which the NLP model is derived. Be sure to download the dataset beforehand by `$ python -m spacy download name_of_the_dataset`. `The default is "en_core_web_lg".
DATA_DATASET: "en_core_web_lg"

# LoggerConfig.prop setting. The directory containing the log files, relevant to the project's root. The default is ".logs".
LOGGER_DIR: ".logs"

# LoggerConfig.prop setting. The filename of the accumulated debug log. The default is "debug.log".
LOGGER_FILE_DEBUG: "debug.log"

# LoggerConfig.prop setting. The filename of the last run's log. The default is "last.log".
LOGGER_FILE_LAST: "last.log"

# LoggerConfig.prop setting. The filename of the test-driven log. The default is "test.log".
LOGGER_FILE_TEST: "test.log"

# LoggerConfig.prop setting. The format of the logger. The default is:
# [%(asctime)s][%(module)s:%(funcName)s:%(lineno)d][%(levelname)s] %(message)s
LOGGER_FORMAT: "[%(asctime)s][%(module)s:%(funcName)s:%(lineno)d][%(levelname)s] %(message)s"

# LoggerConfig.prop setting. The level of the logger. The default is 20.
# DEBUG=10, INFO=20, WARN=30, ERROR=40, CRITICAL=50
LOGGER_LEVEL: 20

# PatternSetConfig.prop setting. The file extension of the patternsets. The default is "yaml".
PATTERN_SET_FILE_EXTENSION: "yaml"

# PatternSetConfig.prop setting . The name of the directory containing the patternset files. The default is "patterns".
PATTERN_SET_HOST_DIR: "patternsets"

# PatternSetConfigVal.prop setting. The value of the `how_many_matches` setting representing all matches. Changing this setting changes the corresponding value of the setting in the patternset files.
PATTERN_SET_ALL_MATCHES: "all"

# PatternSetConfigVal.prop setting. The value of the `how_many_matches` setting representing one match. Changing this setting changes the corresponding value of the setting in the patternset files.
PATTERN_SET_ONE_MATCH: "one"

# NYI. PatternSetConfigVal.prop setting. The value of the `best_match` setting representing the last match. Changing this setting changes the corresponding value of the setting in the patternset files.
PATTERN_SET_FIRST_MATCH: "first"

# NYI. PatternSetConfigVal.prop setting. The value of the `best_match` setting representing the first match. Changing this setting changes the corresponding value of the setting in the patternset files.
PATTERN_SET_LAST_MATCH: "last"

# PatternSetConfigVal.prop setting. The value of the `best_match` setting representing the longest match. Changing this setting changes the corresponding value of the setting in the patternset files.
PATTERN_SET_LONGEST_MATCH: "longest"

# NYI. PatternSetConfigVal.prop setting. The value of the `best_match` setting representing the shortest match. Changing this setting changes the corresponding value of the setting in the patternset files.
PATTERN_SET_SHORTEST_MATCH: "shortest"

# PatternSetConfigVal.prop setting. The default value of the setting representing the expected number of matches. Changing this setting changes the corresponding value of the setting in the patternset files.
PATTERN_SET_DEFAULT_HOW_MANY_MATCHES: "all"

# PatternSetConfigVal.prop setting. The default value of the setting representing the best match. Changing this setting changes the corresponding value of the setting in the patternset files.
PATTERN_SET_DEFAULT_BEST_MATCH: "longest"
