---
# This example describes how to create and configure patternsets. An example with notes is also available.

meta:
    extract_noun_chunks: false
    how_many_matches: one
    skip_tests: false

patterns:
    - rulename: present simple
      tokens:
          - {TAG: {IN: ["VBP", "VBZ"]}, OP: "+"}

    - rulename: present simple passive
      tokens:
          - {
              TAG: {IN: ["VBP", "VBZ"]},
              DEP: "auxpass",
              LEMMA: "be",
              OP: "+"
          }
          - {TAG: "VBN", OP: "+"}

    - rulename: future simple be-going-to
      tokens:
          - {TAG: {IN: ["VBP", "VBZ"]}, DEP: "aux", OP: "+"}
          - {TAG: "VBG", OP: "+", LEMMA: "go"}
          - {TAG: "TO", DEP: "aux", OP: "+"}
          - {TAG: "VB", DEP: "xcomp", OP: "+"}

tests:
    - input: I run.
      rulenames:
          - present simple
      spans:
          - run
      skip: false

    - input: He runs.
      rulenames:
          - present simple
      spans:
          - runs
      skip: true

    - input: She runs.
      rulenames:
          - present simple
      spans:
          - runs

    - input: They run.
      rulenames:
          - present simple
      spans:
          - run

    - input: I am going to run.
      rulenames:
          - future simple be-going-to
      spans:
          - am going to run
